export default {
  html: [],
  head: [],
  title: [],
  style: [],
  link: ['href', 'rel'],
  body: ['style', 'class'],
  a: ['target', 'href', 'title', 'style', 'class'],
  abbr: ['title', 'style', 'class'],
  address: ['style', 'class'],
  area: ['shape', 'coords', 'href', 'alt', 'style', 'class'],
  article: ['style', 'class'],
  aside: ['style', 'class'],
  audio: [
    'autoplay',
    'controls',
    'crossorigin',
    'loop',
    'muted',
    'preload',
    'src',
  ],
  b: ['style', 'class'],
  bdi: ['dir', 'style', 'class'],
  bdo: ['dir', 'style', 'class'],
  big: ['style', 'class'],
  blockquote: ['cite', 'style', 'class'],
  br: ['style', 'class'],
  caption: ['style', 'class'],
  center: ['style', 'class'],
  cite: ['style', 'class'],
  code: ['style', 'class'],
  col: ['align', 'valign', 'span', 'width', 'style', 'class'],
  colgroup: ['align', 'valign', 'span', 'width', 'style', 'class'],
  dd: ['style', 'class'],
  del: ['datetime', 'style', 'class'],
  details: ['open', 'style', 'class'],
  div: ['style', 'class'],
  dl: ['style', 'class'],
  dt: ['style', 'class'],
  em: ['style', 'class'],
  figcaption: ['style', 'class'],
  figure: ['style', 'class'],
  font: ['color', 'size', 'face', 'style', 'class'],
  footer: ['style', 'class'],
  h1: ['style', 'class'],
  h2: ['style', 'class'],
  h3: ['style', 'class'],
  h4: ['style', 'class'],
  h5: ['style', 'class'],
  h6: ['style', 'class'],
  header: ['style', 'class'],
  hr: ['style', 'class'],
  i: ['style', 'class'],
  img: ['src', 'alt', 'title', 'width', 'height', 'style', 'class'],
  ins: ['datetime', 'style', 'class'],
  li: ['style', 'class'],
  mark: ['style', 'class'],
  nav: ['style', 'class'],
  ol: ['style', 'class'],
  p: ['style', 'class'],
  pre: ['style', 'class'],
  s: ['style', 'class'],
  section: ['style', 'class'],
  small: ['style', 'class'],
  span: ['style', 'class'],
  sub: ['style', 'class'],
  summary: ['style', 'class'],
  sup: ['style', 'class'],
  strong: ['style', 'class'],
  strike: ['style', 'class'],
  table: ['width', 'border', 'align', 'valign', 'style', 'class'],
  tbody: ['align', 'valign', 'style', 'class'],
  td: ['width', 'rowspan', 'colspan', 'align', 'valign', 'style', 'class'],
  tfoot: ['align', 'valign', 'style', 'class'],
  th: ['width', 'rowspan', 'colspan', 'align', 'valign', 'style', 'class'],
  thead: ['align', 'valign', 'style', 'class'],
  tr: ['rowspan', 'align', 'valign', 'style', 'class'],
  tt: ['style', 'class'],
  u: ['style', 'class'],
  ul: ['style', 'class'],
  video: [
    'autoplay',
    'controls',
    'crossorigin',
    'loop',
    'muted',
    'playsinline',
    'poster',
    'preload',
    'src',
    'height',
    'width',
    'style',
    'class',
  ],
};
